name: Node Continuous Integration

on:
  pull_request:
    branches: [ main ]


jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: cd 225-github-actions-demo && npm ci
      - run: cd 225-github-actions-demo && npm test
      - run: cd 225-github-actions-demo && npm run build